language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install nose pep8
# command to run tests
script: 
  - nosetests
  - pep8 --max-line-length=120 .
